sudo: false
language: node_js
node_js:
  - "8"
notifications:
  disabled: true
script: echo "Script Running"
deploy:
  provider: script
  script: DEBUG=glitch-deploy* npx glitch-deploy
  on:
    branch: master
